# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sitwitus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sitwitus

pod 'IQKeyboardManagerSwift'

pod 'LocationPickerViewController'

pod 'GoogleMaps'

pod 'HCSStarRatingView'

end
